# Generated by Django 6.0.6 on 2026-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('health_issues', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Доступен для помощи'), ('adopted', 'Взят домой'), ('foster', 'Взят на передержку')], max_length=20)),
                ('photo', models.CharField(max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
