# Generated by Django 6.0.6 on 2026-06-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_pet_age_pet_approximate_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
