# Generated by Django 6.0.6 on 2026-06-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_pet_approximate_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в базу'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health_issues',
            field=models.BooleanField(default=False, verbose_name='Есть проблемы со здоровьем'),
        ),
    ]
