# Generated by Django 6.0.6 on 2026-06-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_pet_created_at_alter_pet_health_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='created_at',
        ),
    ]
