# Generated by Django 6.0.6 on 2026-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_pet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта забравшего'),
        ),
        migrations.AddField(
            model_name='pet',
            name='new_owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО забравшего'),
        ),
        migrations.AddField(
            model_name='pet',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон забравшего'),
        ),
        migrations.AddField(
            model_name='pet',
            name='taken_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата забирания'),
        ),
    ]
