# Generated by Django 6.0.6 on 2026-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_pet_mail_pet_new_owner_pet_phone_pet_taken_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='treatment_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Описание лечения'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен для помощи'), ('adopted', 'Взят домой'), ('foster', 'Взят на передержку'), ('treatment', 'Нуждается в лечении')], max_length=20, verbose_name='Статус'),
        ),
    ]
