services:
  db:
    image: postgres:17

    environment:
      POSTGRES_DB: ${ENV_DB_NAME}
      POSTGRES_USER: ${ENV_DB_USER}
      POSTGRES_PASSWORD: ${ENV_DB_PASSWORD}

    ports:
      - ${ENV_DB_PORT}:${ENV_DB_PORT}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .

    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db

volumes:
  postgres_data: