# Generated by Django 6.0.6 on 2026-06-20 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_pet_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='approximate_birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
