# Generated by Django 6.0.6 on 2026-06-20 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_pet_photo_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='approximate_birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения (приблизительно)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health_issues',
            field=models.BooleanField(default=False, verbose_name='Проблемы со здоровьем'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен для помощи'), ('adopted', 'Взят домой'), ('foster', 'Взят на передержку')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='video',
            field=models.CharField(blank=True, max_length=255, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
    ]
